---

plugin: aws_ec2

# Filtres sur la région et les tags voulus
regions:
  - us-east-1


# Grouper les instances par Nom
keyed_groups:
 - key: tags.Name
   separator: ''
   prefix: ''


hostnames:
# a list in order of precedence for hostname variables.
     - ip-address
     - dns-name
     - tag:Name
