---

- name: Install monitoring tools
  hosts: administration
  remote_user: ec2-user
  become: yes
  roles:
    - role: 'docker'
      when: "{{install_docker}} "

    - role: 'prometheus'
      when: "{{install_prometheus}} "

    - role: 'grafana'
      when: "{{install_grafana}} "



