---

- name: Monitoring using prometheus, zoonavigator, landoop UI
  hosts: administration
  remote_user: ec2-user
  become: yes
  vars_files:
     - "./vars/{{env}}.yaml"
  tasks:
     - name: install java 8 
       yum:
         name: "java-{{java.version}}-openjdk-devel"
         state: latest

     - name: Check the prometheus directory exists
       stat:
         path: /home/ec2-user/prometheus
       register: prometheus_dir  
                
     - name: Download prometheus 
       get_url:
         url: "https://github.com/prometheus/prometheus/releases/download/v2.36.2/prometheus-2.36.2.linux-amd64.tar.gz"
         dest: /tmp/
       when: not prometheus_dir.stat.exists
         
     - name: Extract prometheus tar
       unarchive:
         remote_src: yes
         src: /tmp/prometheus-2.36.2.linux-amd64.tar.gz
         dest: /home/ec2-user
       when: not prometheus_dir.stat.exists
        
     - name:  rename prometheus folder
       command: "mv /home/ec2-user/prometheus-2.36.2.linux-amd64 /home/ec2-user/prometheus"
       when: not prometheus_dir.stat.exists

     - name: Copy /etc/hosts
       copy:
        src: ./vars/hosts
        dest: /etc/hosts
  
     - name: Copy prometheus config file
       copy:
        src: ../prometheus.yml
        dest: ./prometheus/prometheus.yml

     - name: Copy prometheus config file
       copy:
        src: ../docker/{{ item}}
        dest: ./docker/  
       loop:
          - kafka-topics-ui-docker-compose.yaml
          - zoonavigator-docker-compose.yaml

     - name:  Run docker compose on the two files
       command: "docker-compose -f {{ item }} up -d"
       loop:
         - zoonavigator-docker-compose.yaml
         - kafka-topics-ui-docker-compose.yaml
